### ISSUE TITLE
process.stdin.isTTY is undefined

### ISSUE THREAD

**Issue by CKGrafico** [Azure/Azure-WebApps-Support-Center#68]
Using node plugins like [fontmin ](https://github.com/ecomfe/fontmin/blob/master/cli.js) are working well on local machine but when I try to run this plugins using Kudu CMD `process.stdin.isTTY` is undefined.

**Comment by Jen7714** [comment]
Hi @CKGrafico, please open an issue here: https://github.com/projectkudu/kudu
